services:
  ai-expense-chat-server:
    image: ghcr.io/vinzcodz/ai-expense-chat-server:latest
    container_name: ai-expense-chat-server
    restart: unless-stopped

    ports:
      - 3001:3001

    env_file:
      - .env

    environment:
      - NODE_ENV=dev